#Plugin by superpeanut911
#Use Id's only for blocked blocks!
#http://www.minecraftwiki.net/wiki/Data_values - Find block Id's (EX: 7 is bedrock)

#==============================
#        PvP Block           //
#==============================

block-pvp:
  enabled: true
  message: "&cYou cannot PvP in creative mode!"

#==============================
#        Item Drop Block     //
#==============================

block-item-drop:
  enabled: true
  message: "&cYou cannot drop stuff in creative mode!"

#==============================
#   Block Place Blacklist    //
#==============================

place-blacklist:
  enabled: true
  #The blockname is always last, You cannot disable it at this point
  message: "&cYou are not allowed to place "
  blacklist:
  - 7

#==============================
#     Chest Access block     //
#==============================

chest-block:
  enabled: true
  message: "&cYou cannot access chests in creative mode!"


#==============================
#      Command Blacklist     //
#==============================

command-blacklist:
  enabled: true
  message: "&cThat command is not permitted in creative mode!"
  blacklist:
  - sell

#==============================
#           Pickup           //
#==============================

block-pickup:
  enabled: true
  #No msg sent for this one

#==============================
#   Block Break Blacklist    //
#==============================

break-blacklist:
  enabled: true
  #Block name always at the end, Sorry!
  message: "&cYou are not allowed to place "
  blacklist:
  - 7

#==============================
#         Mob Damage         //
#==============================

block-mob-harming:
  enabled: true
  message: "&cYou are not allowed to hurt mobs in creative!"


#==============================
#        END OF CONFIG       //
#==============================