#Plugin by superpeanut911
#Use Id's only for blocked blocks!
#http://www.minecraftwiki.net/wiki/Data_values - Find block Id's (EX: 7 is bedrock)

#==============================
#        PvP Block           //
#==============================

block-pvp:
  enabled: true
  message: "&cYou cannot PvP in creative mode!"

#==============================
#        Item Drop Block     //
#==============================

block-item-drop:
  enabled: true
  message: "&cYou cannot drop stuff in creative mode!"

#==============================
#   Block Place Blacklist    //
#==============================

place-blacklist:
  enabled: true
  #The blockname is always last, You cannot disable it at this point
  message: "&cYou are not allowed to place {BLOCK}!"
  blacklist:
  - 7

#==============================
#     Chest Access block     //
#==============================

chest-block:
  enabled: true
  message: "&cYou cannot access chests in creative mode!"


#==============================
#      Command Blacklist     //
#==============================

command-blacklist:
  enabled: true
  message: "&cThat command is not permitted in creative mode!"
  blacklist:
  - sell

#==============================
#           Pickup           //
#==============================

block-pickup:
  enabled: true
  #No msg sent for this one

#==============================
#   Block Break Blacklist    //
#==============================

break-blacklist:
  enabled: true
  #Block name always at the end, Sorry!
  message: "&cYou are not allowed to break {BLOCK}!"
  blacklist:
  - 7

#==============================
#         Mob Damage         //
#==============================

block-mob-harming:
  enabled: true
  message: "&cYou are not allowed to hurt mobs in creative!"

#==============================
#         Auto Update        //
#==============================

allow-autoupdate:
  enabled: true


#==============================
#      Inventory Split        //
#==============================

inventory-split:
  enabled: true


#==============================
#          Economy        //
#==============================

economy:
  pay-gamemode:
    enabled: false
    #Amout only paid if enabled is true. If player does not have enough they will stay in survival!
    amount: 25
    success: "&cYou have been charged {AMOUNT}&c for changing game modes!"
    failure: "&cYou need {AMOUNT}&c to change game modes!"

#==============================
#          SpawnEggs      //
#==============================
#Note: If you have spawneggs in survival and this check is on, you will still be denied using them
spawnegg:
  enabled: true

#==============================
#        END OF CONFIG       //
#==============================