name: RestrictCreative
main: main.java.net.endercraftbuild.Main
version: 1.5.3-DEV
author: superpeanut911
softdepend: [Vault]
permissions:
    restrictcreative.bypass.*:
        description: Bypass Everything
        children:
            restrictcreative.bypass.pvp: true
            restrictcreative.bypass.placeblacklist: true
            restrictcreative.bypass.breakblacklist: true
            restrictcreative.bypass.drop: true
            restrictcreative.bypass.chests: true
            restrictcreative.bypass.commands: true
            restrictcreative.bypass.pickup: true
            restrictcreative.bypass.mobs: true
    restrictcreative.bypass.pvp:
        description: Allows PvP in creative mode
        default: op
    restrictcreative.bypass.placeblacklist:
        description: Bypass blacklist check
        default: op
    restrictcreative.bypass.drop:
        description: Bypass item drop check
        default: op
    restrictcreative.bypass.chests:
        description: Bypass chest access check
        default: op
    restrictcreative.bypass.commands:
        description: Bypass Command blacklist
        default: op
    restrictcreative.bypass.pickup:
        description: Allows picking stuff up in creative
        default: op
    restrictcreative.bypass.breakblacklist:
        description: Allows PvP in creative mode
        default: op
    restrictcreative.bypass.mobs:
        description: Allows mob hurting
        default: op
    restrictcreative.bypass.paygm:
        description: Dont have to pay for gamemode changes
        default: op
commands:
   rc:
      description: RestrictCreative
      usage: /<command>